package models;

import java.sql.Timestamp;

public class Sale {
    private int id;
    private int productId;
    private int quantitySold;
    private Timestamp saleDate; // To store when the sale occurred

    public Sale(int id, int productId, int quantitySold, Timestamp saleDate) {
        this.id = id;
        this.productId = productId;
        this.quantitySold = quantitySold;
        this.saleDate = saleDate;
    }

    // Constructor for creating new sales (ID and date are often auto-generated by DB)
    public Sale(int productId, int quantitySold) {
        this.productId = productId;
        this.quantitySold = quantitySold;
        // id and saleDate will be set by the database or retrieved later
    }

    // Getters
    public int getId() { return id; }
    public int getProductId() { return productId; }
    public int getQuantitySold() { return quantitySold; }
    public Timestamp getSaleDate() { return saleDate; }

    // No setters for immutability after creation, but can be added if needed for specific logic
}
